name: release
on:
  push:
    branches:
      - 'main'
      - 'beta'
      - 'alpha'
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install deps
        # there's a build step for post installation so we don't run build when "testing"
        run: yarn install
      - name: Lint test 🧪
        run: yarn eslint:ci
      - name: Prettier test
        run: yarn prettier:check
      - name: Type check
        run: yarn types
  release:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'pmndrs/three-stdlib' && contains('refs/heads/main,refs/heads/beta,refs/heads/alpha',github.ref) && github.event_name == 'push' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install deps
        # this runs a build script so there is no dedicated build
        run: yarn install
      - name: 🚀 Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/git
          branches: |
            [
              'master',
              {name: 'beta', prerelease: true},
              {name: 'alpha', prerelease: true}
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
